export const airportCodes = {
  NCE: { country: "France" },
  FAO: { country: "Portugal" },
  PMI: { country: "Spain" },
  MIA: { country: "United States" },
  BOG: { country: "Colombia" },
  OPO: { country: "Portugal" },
  FUE: { country: "Spain" },
  IBZ: { country: "Spain" },
  VLC: { country: "Spain" },
  LPA: { country: "Spain" },
  LHR: { country: "United Kingdom" },
  RHO: { country: "Greece" },
  LCA: { country: "Cyprus" },
  ALC: { country: "Spain" },
  CHQ: { country: "Greece" },
  HRG: { country: "Egypt" },
  PDL: { country: "Portugal" },
  LEJ: { country: "Germany" },
  SHJ: { country: "United Arab Emirates" },
  SIN: { country: "Singapore" },
  NRT: { country: "Japan" },
  ANC: { country: "United States" },
  CDG: { country: "France" },
  PFO: { country: "Cyprus" },
  JTR: { country: "Greece" },
  BOS: { country: "United States" },
  BCN: { country: "Spain" },
  ATL: { country: "United States" },
  ICN: { country: "South Korea" },
  JFK: { country: "United States" },
  DXB: { country: "United Arab Emirates" },
  YYZ: { country: "Canada" },
  BRI: { country: "Italy" },
  BJV: { country: "Turkey" },
  MJT: { country: "Turkey" },
  SMI: { country: "Greece" },
  DTW: { country: "United States" },
  NAP: { country: "Italy" },
  EIN: { country: "Netherlands" },
  PBM: { country: "Suriname" },
  AOK: { country: "Greece" },
  CGK: { country: "Indonesia" },
  KUL: { country: "Malaysia" },
  TFS: { country: "Spain" },
  LJU: { country: "Slovenia" },
  KEF: { country: "Iceland" },
  CAN: { country: "China" },
  ACC: { country: "Ghana" },
  HAM: { country: "Germany" },
  SVQ: { country: "Spain" },
  AGP: { country: "Spain" },
  BRU: { country: "Belgium" },
  EFL: { country: "Greece" },
  DUS: { country: "Germany" },
  BLQ: { country: "Italy" },
  PRG: { country: "Czech Republic" },
  OSL: { country: "Norway" },
  HKG: { country: "Hong Kong" },
  ARN: { country: "Sweden" },
  HAJ: { country: "Germany" },
  GVA: { country: "Switzerland" },
  MAD: { country: "Spain" },
  VIE: { country: "Austria" },
  VRN: { country: "Italy" },
  MUC: { country: "Germany" },
  ZRH: { country: "Switzerland" },
  LIS: { country: "Portugal" },
  MXP: { country: "Italy" },
  MLA: { country: "Malta" },
  CPH: { country: "Denmark" },
  WAW: { country: "Poland" },
  LGW: { country: "United Kingdom" },
  IAD: { country: "United States" },
  HER: { country: "Greece" },
  LCY: { country: "United Kingdom" },
  LIN: { country: "Italy" },
  BLL: { country: "Denmark" },
  ORD: { country: "United States" },
  SKG: { country: "Greece" },
  AAL: { country: "Denmark" },
  BRE: { country: "Germany" },
  NUE: { country: "Germany" },
  BHX: { country: "United Kingdom" },
  LUX: { country: "Luxembourg" },
  SOU: { country: "United Kingdom" },
  EWR: { country: "United States" },
  BER: { country: "Germany" },
  FCO: { country: "Italy" },
  BVC: { country: "Cape Verde" },
  SID: { country: "Cape Verde" },
  FNC: { country: "Portugal" },
  STR: { country: "Germany" },
  ZTH: { country: "Greece" },
  ATH: { country: "Greece" },
  NBE: { country: "Morocco" },
  KRS: { country: "Norway" },
  RAK: { country: "Morocco" },
  YUL: { country: "Canada" },
  BSL: { country: "Switzerland" },
  LYS: { country: "France" },
  DUB: { country: "Ireland" },
  GOT: { country: "Sweden" },
  TPE: { country: "Taiwan" },
  BGO: { country: "Norway" },
  BLR: { country: "India" },
  WRO: { country: "Poland" },
  GLA: { country: "United Kingdom" },
  LPI: { country: "Tanzania" },
  ZNZ: { country: "Tanzania" },
  DAR: { country: "Tanzania" },
  VCE: { country: "Italy" },
  CUR: { country: "Curaçao" },
  SVG: { country: "Norway" },
  BOM: { country: "India" },
  NWI: { country: "United Kingdom" },
  NTE: { country: "France" },
  DPS: { country: "Indonesia" },
  IAH: { country: "United States" },
  YYC: { country: "Canada" },
  FRA: { country: "Germany" },
  DFW: { country: "United States" },
  EDI: { country: "United Kingdom" },
  MAN: { country: "United Kingdom" },
  NBO: { country: "Kenya" },
  UIO: { country: "Ecuador" },
  OTP: { country: "Romania" },
  RUH: { country: "Saudi Arabia" },
  DMM: { country: "Saudi Arabia" },
  SXB: { country: "France" },
  HUY: { country: "United Kingdom" },
  TRN: { country: "Italy" },
  GOA: { country: "India" },
  MNL: { country: "Philippines" },
  ABZ: { country: "United Kingdom" },
  LTN: { country: "United Kingdom" },
  SEA: { country: "United States" },
  GDN: { country: "Poland" },
  TLS: { country: "France" },
  ZAG: { country: "Croatia" },
  NCL: { country: "United Kingdom" },
  BEG: { country: "Serbia" },
  HEL: { country: "Finland" },
  MME: { country: "United Kingdom" },
  BRS: { country: "United Kingdom" },
  LBA: { country: "United Kingdom" },
  PHL: { country: "United States" },
  KRK: { country: "Poland" },
  LPL: { country: "United Kingdom" },
  FLR: { country: "Italy" },
  AES: { country: "Norway" },
  MRS: { country: "France" },
  MSP: { country: "United States" },
  SCL: { country: "Chile" },
  EZE: { country: "Argentina" },
  ORK: { country: "Ireland" },
  BUD: { country: "Hungary" },
  TLV: { country: "Israel" },
  BIO: { country: "Spain" },
  SOF: { country: "Bulgaria" },
  TLL: { country: "Estonia" },
  CWL: { country: "United Kingdom" },
  INV: { country: "United Kingdom" },
  AUA: { country: "Aruba" },
  RIX: { country: "Latvia" },
  SPU: { country: "Croatia" },
  LAX: { country: "United States" },
  SFO: { country: "United States" },
  PDX: { country: "United States" },
  VNO: { country: "Lithuania" },
  GUW: { country: "Norway" },
  TRD: { country: "Norway" },
  BOD: { country: "France" },
  SXM: { country: "Sint Maarten" },
  POS: { country: "Trinidad and Tobago" },
  DEL: { country: "India" },
  YEG: { country: "Canada" },
  ASR: { country: "Turkey" },
  IST: { country: "Turkey" },
  CTG: { country: "Colombia" },
  LIM: { country: "Peru" },
  DOH: { country: "Qatar" },
  SLC: { country: "United States" },
  JRO: { country: "Tanzania" },
  CPT: { country: "South Africa" },
  CMN: { country: "Morocco" },
  JNB: { country: "South Africa" },
  AUS: { country: "United States" },
  DWC: { country: "United Arab Emirates" },
  BQN: { country: "Puerto Rico" },
  EBL: { country: "Iraq" },
  PVG: { country: "China" },
  KGL: { country: "Rwanda" },
  EBB: { country: "Uganda" },
  LAS: { country: "United States" },
  SAW: { country: "Turkey" },
  BON: { country: "Bonaire" },
  STN: { country: "United Kingdom" },
  NDR: { country: "Germany" },
  AYT: { country: "Turkey" },
  YVR: { country: "Canada" },
  POZ: { country: "Poland" },
  PTY: { country: "Panama" },
  JED: { country: "Saudi Arabia" },
  GIG: { country: "Brazil" },
  GYE: { country: "Ecuador" },
  NKG: { country: "China" },
  GYD: { country: "Azerbaijan" },
  CAI: { country: "Egypt" },
  RMF: { country: "Egypt" },
  MPL: { country: "France" },
  GRU: { country: "Brazil" },
  RNS: { country: "France" },
  MEX: { country: "Mexico" },
  SPC: { country: "Spain" },
  KIX: { country: "Japan" },
  LOS: { country: "Nigeria" },
  AMM: { country: "Jordan" },
  ERF: { country: "Germany" },
  ZIA: { country: "Pakistan" },
};

export const getCountryByAirportCode = (code) => {
  const airport = airportCodes[code];
  return airport ? airport.country : "Unknown";
};
